[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

solc_version = "0.8.20"
optimizer = true
optimizer_runs = 999999